# Generated by Django 4.1.2 on 2024-01-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('About', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Non-IT', 'Non-IT'), ('Mobile Phones', 'Mobile Phones')], max_length=100)),
                ('JoinDate', models.DateField(auto_now=True)),
                ('Working', models.BooleanField(default=False)),
            ],
        ),
    ]
