# Generated by Django 4.1.2 on 2024-01-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Working',
            new_name='Active',
        ),
    ]
